[tox]
envlist =
    lint
    py{39,310,311,312,313}
isolated_build = true

[testenv:py]
deps=
    pytest
    requests-cache
    coverage
commands=
    python -m pytest

[testenv:lint]
skip_install = true
deps =
    ruff
    black
    codespell
commands =
    ruff check
    black --check --diff .
    codespell

[testenv:format]
skip_install = true
deps =
    ruff
    black
    codespell
commands =
    ruff check --fix
    black .
    codespell


