[tox]
envlist = py39, py310, py311, py312, py313
isolated_build = true

[testenv]
deps=
    pytest
    requests-cache
    coverage
commands=
    python -m pytest

[lint]
skip_install = true
deps =
    ruff
    black
    codespell
commands =
    ruff check
    black --check --diff .
    codespell

[format]
skip_install = true
deps =
    ruff
    black
    codespell
commands =
    ruff check --fix
    black .
    codespell


